import { useEffect, useState } from 'react'
import {
  Wallet, Plus, Receipt, TrendingUp, TrendingDown, FileWarning, CheckCircle2,
  BellRing, Bell, Printer, X, AlertCircle
} from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { feeAPI, studentAPI } from '../services/api'
import { formatDate, formatDateTime } from '../utils/helpers'
import { Loader, EmptyState, Badge, Modal, StatCard } from '../components/ui'
import CustomSelect from '../components/ui/CustomSelect'
import ReceiptPrintModal from '../components/ReceiptPrintModal'

const METHOD_OPTIONS = ['CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'ONLINE', 'CHEQUE'].map(m => ({ value: m, label: m }))

export default function FeesPage() {
  const { user } = useAuth()
  if (user?.role === 'STUDENT') return <StudentFeesView />
  return <StaffFeesView />
}

// ── Student view ──────────────────────────────────────────────
function StudentFeesView() {
  const { user } = useAuth()
  const [invoices, setInvoices] = useState([])
  const [reminders, setReminders] = useState([])
  const [loading, setLoading] = useState(true)
  const [viewing, setViewing] = useState(null)
  const [payments, setPayments] = useState(null)
  const [receiptFor, setReceiptFor] = useState(null)

  const load = () => {
    if (!user?.profileId) return
    setLoading(true)
    Promise.all([feeAPI.getStudentInvoices(user.profileId), feeAPI.myReminders()])
      .then(([i, r]) => { setInvoices(i.data); setReminders(r.data) })
      .finally(() => setLoading(false))
  }

  useEffect(() => { load() }, [user])

  const openInvoice = (inv) => {
    setViewing(inv)
    setPayments(null)
    feeAPI.getPayments(inv.id).then(res => setPayments(res.data))
  }

  const dismissReminder = async (id) => {
    await feeAPI.markReminderRead(id)
    setReminders(rs => rs.map(r => r.id === id ? { ...r, isRead: true } : r))
  }

  if (loading) return <Loader full />

  const totalDue = invoices.reduce((s, i) => s + i.amountDue, 0)
  const totalPaid = invoices.reduce((s, i) => s + i.amountPaid, 0)
  const unreadReminders = reminders.filter(r => !r.isRead)

  return (
    <div>
      <div className="page-header">
        <div className="page-header-left">
          <h1 className="page-title">My Fees</h1>
          <p className="page-subtitle">Your invoices and payment history</p>
        </div>
      </div>

      {unreadReminders.length > 0 && (
        <div className="reminder-banner-list">
          {unreadReminders.map(r => (
            <div className="reminder-banner" key={r.id}>
              <BellRing size={16} />
              <div className="reminder-banner-body">
                <div className="reminder-banner-msg">{r.message}</div>
                <div className="reminder-banner-meta">Sent {formatDateTime(r.sentAt)} · {r.invoice?.invoiceNumber}</div>
              </div>
              <button className="btn btn-ghost btn-icon btn-sm" onClick={() => dismissReminder(r.id)}><X size={14} /></button>
            </div>
          ))}
        </div>
      )}

      <div className="stat-grid" style={{ marginBottom: 20 }}>
        <StatCard label="Total Billed" value={`₹${totalDue.toLocaleString('en-IN')}`} icon={Wallet} color="var(--accent)" />
        <StatCard label="Total Paid" value={`₹${totalPaid.toLocaleString('en-IN')}`} icon={CheckCircle2} color="var(--success)" />
        <StatCard label="Outstanding" value={`₹${(totalDue - totalPaid).toLocaleString('en-IN')}`} icon={FileWarning} color="var(--warning)" />
      </div>

      {invoices.length === 0 ? (
        <EmptyState icon={Wallet} title="No invoices yet" subtitle="Your fee invoices will appear here once generated by Accounts." />
      ) : (
        <div className="table-wrap">
          <table className="table">
            <thead><tr><th>Invoice #</th><th>Semester</th><th>Due Date</th><th>Amount Due</th><th>Amount Paid</th><th>Status</th><th></th></tr></thead>
            <tbody>
              {invoices.map(inv => (
                <tr key={inv.id}>
                  <td>{inv.invoiceNumber}</td>
                  <td>Sem {inv.semester} · {inv.academicYear}</td>
                  <td>{formatDate(inv.dueDate)}</td>
                  <td>₹{inv.amountDue.toLocaleString('en-IN')}</td>
                  <td>₹{inv.amountPaid.toLocaleString('en-IN')}</td>
                  <td><Badge value={inv.status} /></td>
                  <td><button className="btn btn-ghost btn-sm" onClick={() => openInvoice(inv)}>View</button></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {viewing && (
        <Modal title={`Invoice ${viewing.invoiceNumber}`} onClose={() => setViewing(null)}>
          <p className="page-subtitle" style={{ marginBottom: 16 }}>
            Amount due ₹{viewing.amountDue.toLocaleString('en-IN')} · Paid ₹{viewing.amountPaid.toLocaleString('en-IN')}
          </p>
          <div className="sc-title" style={{ marginBottom: 10 }}>Payment history</div>
          {!payments ? <Loader /> : payments.length === 0 ? (
            <EmptyState icon={Receipt} title="No payments recorded yet" />
          ) : (
            <div className="cc-item-list">
              {payments.map(p => (
                <div className="cc-item" key={p.id}>
                  <div className="cc-item-icon"><Receipt size={16} /></div>
                  <div className="cc-item-body">
                    <div className="cc-item-title">₹{p.amount.toLocaleString('en-IN')} · {p.method}</div>
                    <div className="cc-item-meta">{p.receiptNumber} · {formatDate(p.paymentDate)}</div>
                  </div>
                  <button className="btn btn-ghost btn-sm" onClick={() => setReceiptFor(p)}>
                    <Printer size={13} /> Receipt
                  </button>
                </div>
              ))}
            </div>
          )}
        </Modal>
      )}

      {receiptFor && (
        <ReceiptPrintModal invoice={viewing} payment={receiptFor} onClose={() => setReceiptFor(null)} />
      )}
    </div>
  )
}

// ── Accounts / Admin view ───────────────────────────────────────
function StaffFeesView() {
  const [tab, setTab] = useState('invoices')
  const [summary, setSummary] = useState(null)
  const [invoices, setInvoices] = useState([])
  const [structures, setStructures] = useState([])
  const [loading, setLoading] = useState(true)
  const [showInvoiceForm, setShowInvoiceForm] = useState(false)
  const [showStructureForm, setShowStructureForm] = useState(false)
  const [payingInvoice, setPayingInvoice] = useState(null)
  const [remindingInvoice, setRemindingInvoice] = useState(null)
  const [payments, setPayments] = useState(null)
  const [payingHistoryFor, setPayingHistoryFor] = useState(null)
  const [receiptFor, setReceiptFor] = useState(null)

  const load = () => {
    setLoading(true)
    Promise.all([feeAPI.duesSummary(), feeAPI.getAllInvoices(), feeAPI.getStructures()])
      .then(([s, i, st]) => { setSummary(s.data); setInvoices(i.data); setStructures(st.data) })
      .finally(() => setLoading(false))
  }
  useEffect(() => { load() }, [])

  const openHistory = (inv) => {
    setPayingHistoryFor(inv)
    setPayments(null)
    feeAPI.getPayments(inv.id).then(res => setPayments(res.data))
  }

  if (loading) return <Loader full />

  return (
    <div>
      <div className="page-header">
        <div className="page-header-left">
          <h1 className="page-title">Fee Management</h1>
          <p className="page-subtitle">Fee structures, invoices, payments, reminders and receipts</p>
        </div>
        <div style={{ display: 'flex', gap: 10 }}>
          <button className="btn btn-secondary" onClick={() => setShowStructureForm(true)}><Plus size={15} /> Fee Structure</button>
          <button className="btn btn-primary" onClick={() => setShowInvoiceForm(true)}><Plus size={15} /> Generate Invoice</button>
        </div>
      </div>

      {summary && (
        <div className="stat-grid" style={{ marginBottom: 20 }}>
          <StatCard label="Total Collected" value={`₹${summary.totalCollected.toLocaleString('en-IN')}`} icon={TrendingUp} color="var(--success)" />
          <StatCard label="Outstanding" value={`₹${summary.totalOutstanding.toLocaleString('en-IN')}`} icon={TrendingDown} color="var(--warning)" />
          <StatCard label="Pending Invoices" value={summary.pendingCount} icon={FileWarning} color="var(--danger)" />
          <StatCard label="Fully Paid" value={summary.paidCount} icon={CheckCircle2} color="var(--accent)" />
        </div>
      )}

      <div className="tabs" style={{ marginBottom: 16 }}>
        <button className={`tab-btn${tab === 'invoices' ? ' active' : ''}`} onClick={() => setTab('invoices')}>Invoices</button>
        <button className={`tab-btn${tab === 'structures' ? ' active' : ''}`} onClick={() => setTab('structures')}>Fee Structures</button>
      </div>

      {tab === 'invoices' && (
        invoices.length === 0 ? <EmptyState icon={Wallet} title="No invoices yet" /> : (
          <div className="table-wrap">
            <table className="table">
              <thead><tr><th>Invoice #</th><th>Student</th><th>Due Date</th><th>Amount Due</th><th>Paid</th><th>Status</th><th></th></tr></thead>
              <tbody>
                {invoices.map(inv => (
                  <tr key={inv.id}>
                    <td>{inv.invoiceNumber}</td>
                    <td>{inv.student?.name} ({inv.student?.rollNumber})</td>
                    <td>{formatDate(inv.dueDate)}</td>
                    <td>₹{inv.amountDue.toLocaleString('en-IN')}</td>
                    <td>₹{inv.amountPaid.toLocaleString('en-IN')}</td>
                    <td><Badge value={inv.status} /></td>
                    <td>
                      <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                        {inv.status !== 'PAID' && (
                          <>
                            <button className="btn btn-primary btn-xs" onClick={() => setPayingInvoice(inv)}>Record Payment</button>
                            <button className="btn btn-ghost btn-xs" onClick={() => setRemindingInvoice(inv)}>
                              <Bell size={12} /> Remind
                            </button>
                          </>
                        )}
                        {inv.amountPaid > 0 && (
                          <button className="btn btn-ghost btn-xs" onClick={() => openHistory(inv)}>Receipts</button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )
      )}

      {tab === 'structures' && (
        structures.length === 0 ? <EmptyState icon={Wallet} title="No fee structures yet" /> : (
          <div className="table-wrap">
            <table className="table">
              <thead><tr><th>Academic Year</th><th>Semester</th><th>Amount</th><th>Description</th></tr></thead>
              <tbody>
                {structures.map(fs => (
                  <tr key={fs.id}>
                    <td>{fs.academicYear}</td>
                    <td>{fs.semester}</td>
                    <td>₹{fs.totalAmount.toLocaleString('en-IN')}</td>
                    <td>{fs.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )
      )}

      {showInvoiceForm && (
        <InvoiceFormModal structures={structures} onClose={() => setShowInvoiceForm(false)} onDone={() => { setShowInvoiceForm(false); load() }} />
      )}
      {showStructureForm && (
        <StructureFormModal onClose={() => setShowStructureForm(false)} onDone={() => { setShowStructureForm(false); load() }} />
      )}
      {payingInvoice && (
        <PaymentFormModal invoice={payingInvoice} onClose={() => setPayingInvoice(null)} onDone={() => { setPayingInvoice(null); load() }} />
      )}
      {remindingInvoice && (
        <ReminderModal invoice={remindingInvoice} onClose={() => setRemindingInvoice(null)} />
      )}
      {payingHistoryFor && (
        <Modal title={`Receipts — ${payingHistoryFor.invoiceNumber}`} onClose={() => setPayingHistoryFor(null)}>
          {!payments ? <Loader /> : payments.length === 0 ? (
            <EmptyState icon={Receipt} title="No payments recorded yet" />
          ) : (
            <div className="cc-item-list">
              {payments.map(p => (
                <div className="cc-item" key={p.id}>
                  <div className="cc-item-icon"><Receipt size={16} /></div>
                  <div className="cc-item-body">
                    <div className="cc-item-title">₹{p.amount.toLocaleString('en-IN')} · {p.method}</div>
                    <div className="cc-item-meta">{p.receiptNumber} · {formatDate(p.paymentDate)} · by {p.receivedBy}</div>
                  </div>
                  <button className="btn btn-ghost btn-sm" onClick={() => setReceiptFor(p)}>
                    <Printer size={13} /> Print
                  </button>
                </div>
              ))}
            </div>
          )}
        </Modal>
      )}
      {receiptFor && (
        <ReceiptPrintModal invoice={payingHistoryFor} payment={receiptFor} onClose={() => setReceiptFor(null)} />
      )}
    </div>
  )
}

function ReminderModal({ invoice, onClose }) {
  const remaining = invoice.amountDue - invoice.amountPaid
  const [message, setMessage] = useState('')
  const [sending, setSending] = useState(false)
  const [sent, setSent] = useState(false)

  const submit = async (e) => {
    e.preventDefault()
    setSending(true)
    try {
      await feeAPI.sendReminder(invoice.id, message.trim() || undefined)
      setSent(true)
    } finally {
      setSending(false)
    }
  }

  return (
    <Modal title={`Send Reminder — ${invoice.student?.name}`} onClose={onClose}>
      {sent ? (
        <div className="contact-success">
          <CheckCircle2 size={32} />
          <h3>Reminder sent</h3>
          <p>{invoice.student?.name} will see this the next time they open My Fees.</p>
          <button className="btn btn-secondary" onClick={onClose}>Close</button>
        </div>
      ) : (
        <form onSubmit={submit}>
          <div className="alert alert-warning" style={{ marginBottom: 16 }}>
            <AlertCircle size={15} />
            Outstanding balance: ₹{remaining.toLocaleString('en-IN')} on invoice {invoice.invoiceNumber}
          </div>
          <div className="form-group">
            <label className="form-label">Custom message (optional)</label>
            <textarea className="form-textarea" rows={4} value={message} onChange={e => setMessage(e.target.value)}
              placeholder="Leave blank to send the default auto-generated reminder message" />
          </div>
          <div className="modal-footer">
            <button type="button" className="btn btn-ghost" onClick={onClose}>Cancel</button>
            <button type="submit" className="btn btn-primary" disabled={sending}>
              <BellRing size={14} /> {sending ? 'Sending…' : 'Send Reminder'}
            </button>
          </div>
        </form>
      )}
    </Modal>
  )
}

function InvoiceFormModal({ structures, onClose, onDone }) {
  const [studentQuery, setStudentQuery] = useState('')
  const [students, setStudents] = useState([])
  const [studentId, setStudentId] = useState('')
  const [amountDue, setAmountDue] = useState('')
  const [dueDate, setDueDate] = useState('')
  const [feeStructureId, setFeeStructureId] = useState('')
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    studentAPI.getAll({ size: 200 }).then(res => setStudents(res.data.content || res.data))
  }, [])

  const applyStructure = (id) => {
    setFeeStructureId(id)
    const s = structures.find(x => String(x.id) === String(id))
    if (s) setAmountDue(String(s.totalAmount))
  }

  const submit = async (e) => {
    e.preventDefault()
    if (!studentId || !amountDue) return
    setSaving(true)
    try {
      await feeAPI.createInvoice({ studentId, amountDue: Number(amountDue), dueDate: dueDate || null, feeStructureId: feeStructureId || null })
      onDone()
    } finally {
      setSaving(false)
    }
  }

  const filtered = students.filter(s => s.name.toLowerCase().includes(studentQuery.toLowerCase()) || s.rollNumber.toLowerCase().includes(studentQuery.toLowerCase()))

  return (
    <Modal title="Generate Invoice" onClose={onClose}>
      <form onSubmit={submit}>
        <div className="form-group">
          <label className="form-label">Student</label>
          <input className="form-input" placeholder="Search by name or roll no." value={studentQuery}
            onChange={e => setStudentQuery(e.target.value)} style={{ marginBottom: 8 }} />
          <CustomSelect value={studentId} onChange={setStudentId}
            options={filtered.slice(0, 30).map(s => ({ value: String(s.id), label: `${s.name} (${s.rollNumber})` }))}
            placeholder="Select student" />
        </div>
        {structures.length > 0 && (
          <div className="form-group">
            <label className="form-label">Fee structure (optional — auto-fills amount)</label>
            <CustomSelect value={feeStructureId} onChange={applyStructure}
              options={structures.map(s => ({ value: String(s.id), label: `${s.academicYear} · Sem ${s.semester} · ₹${s.totalAmount}` }))}
              placeholder="None" />
          </div>
        )}
        <div className="form-row">
          <div className="form-group">
            <label className="form-label">Amount Due (₹)</label>
            <input className="form-input" type="number" value={amountDue} onChange={e => setAmountDue(e.target.value)} required />
          </div>
          <div className="form-group">
            <label className="form-label">Due Date</label>
            <input className="form-input" type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} />
          </div>
        </div>
        <div className="modal-footer">
          <button type="button" className="btn btn-ghost" onClick={onClose}>Cancel</button>
          <button type="submit" className="btn btn-primary" disabled={saving}>{saving ? 'Creating…' : 'Generate Invoice'}</button>
        </div>
      </form>
    </Modal>
  )
}

function StructureFormModal({ onClose, onDone }) {
  const [form, setForm] = useState({ academicYear: '', semester: '', totalAmount: '', description: '' })
  const [saving, setSaving] = useState(false)

  const submit = async (e) => {
    e.preventDefault()
    if (!form.academicYear || !form.semester || !form.totalAmount) return
    setSaving(true)
    try {
      await feeAPI.createStructure({ ...form, semester: Number(form.semester), totalAmount: Number(form.totalAmount) })
      onDone()
    } finally {
      setSaving(false)
    }
  }

  return (
    <Modal title="Add Fee Structure" onClose={onClose}>
      <form onSubmit={submit}>
        <div className="form-row">
          <div className="form-group">
            <label className="form-label">Academic Year</label>
            <input className="form-input" placeholder="2025-2026" value={form.academicYear}
              onChange={e => setForm(f => ({ ...f, academicYear: e.target.value }))} required />
          </div>
          <div className="form-group">
            <label className="form-label">Semester</label>
            <input className="form-input" type="number" min={1} max={8} value={form.semester}
              onChange={e => setForm(f => ({ ...f, semester: e.target.value }))} required />
          </div>
        </div>
        <div className="form-group">
          <label className="form-label">Total Amount (₹)</label>
          <input className="form-input" type="number" value={form.totalAmount}
            onChange={e => setForm(f => ({ ...f, totalAmount: e.target.value }))} required />
        </div>
        <div className="form-group">
          <label className="form-label">Description</label>
          <input className="form-input" value={form.description}
            onChange={e => setForm(f => ({ ...f, description: e.target.value }))} placeholder="Tuition + lab fees" />
        </div>
        <div className="modal-footer">
          <button type="button" className="btn btn-ghost" onClick={onClose}>Cancel</button>
          <button type="submit" className="btn btn-primary" disabled={saving}>{saving ? 'Saving…' : 'Add Structure'}</button>
        </div>
      </form>
    </Modal>
  )
}

function PaymentFormModal({ invoice, onClose, onDone }) {
  const remaining = invoice.amountDue - invoice.amountPaid
  const [amount, setAmount] = useState(String(remaining))
  const [method, setMethod] = useState('CASH')
  const [transactionRef, setTransactionRef] = useState('')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  const submit = async (e) => {
    e.preventDefault()
    setError('')
    if (!amount || Number(amount) <= 0) return
    setSaving(true)
    try {
      await feeAPI.recordPayment(invoice.id, { amount: Number(amount), method, transactionRef })
      onDone()
    } catch (err) {
      setError(err.response?.data?.message || 'Could not record payment')
    } finally {
      setSaving(false)
    }
  }

  return (
    <Modal title={`Record Payment — ${invoice.invoiceNumber}`} onClose={onClose}>
      <p className="page-subtitle" style={{ marginBottom: 16 }}>
        Remaining balance: ₹{remaining.toLocaleString('en-IN')}
      </p>
      <form onSubmit={submit}>
        <div className="form-group">
          <label className="form-label">Amount (₹)</label>
          <input className="form-input" type="number" value={amount} onChange={e => setAmount(e.target.value)} required />
        </div>
        <div className="form-group">
          <label className="form-label">Method</label>
          <CustomSelect value={method} onChange={setMethod} options={METHOD_OPTIONS} />
        </div>
        <div className="form-group">
          <label className="form-label">Transaction reference (optional)</label>
          <input className="form-input" value={transactionRef} onChange={e => setTransactionRef(e.target.value)} />
        </div>
        {error && <div className="alert alert-danger" style={{ marginBottom: 14 }}>{error}</div>}
        <div className="modal-footer">
          <button type="button" className="btn btn-ghost" onClick={onClose}>Cancel</button>
          <button type="submit" className="btn btn-primary" disabled={saving}>{saving ? 'Recording…' : 'Record Payment'}</button>
        </div>
      </form>
    </Modal>
  )
}
